const RULES_DATABASE = [
    {
        "page": "Page 60",
        "title": "It is now Red\u2019s turn to activate a vehicle. She points at the Red car and picks up the",
        "text": "59\nIt is now Red\u2019s turn to activate a vehicle. She points at the Red car and picks up the\nmedium straight. Placing it down, it is immediately clear that there\u2019s going to be a\nCollision, just as she planned. This movement template is Trivial in Gear 1, but Red\nwants to increase her speed, to ensure maximum carnage in the ensuing head-on crash.\nShe declares and rolls three Skid Dice, which is the maximum her Handling of 3 will\nallow. She rolls two Shifts and a Slide. She uses the free Shift from the template to cancel\nthe Slide result and uses the two Shifts from the Skid Dice to move up Gear twice,\ngaining two Hazard Tokens. Red is now in Gear 3.\nAs Red\u2019s movement template or Final Position overlaps an obstruction (Blue\u2019s car),\nshe pushes the vehicle as far down the template as it will go and resolves a Collision. Red\ndeclares a Smash Attack, as does Blue. The vehicles are both Middleweight, and as Red\nhas crashed her front edge into a corner on Blue\u2019s front edge, the Collision is Head-on."
    },
    {
        "page": "Page 61",
        "title": "Because of this, the vehicles add their Gears together, and both cars roll (Gear 2 + Gear",
        "text": "60\nBecause of this, the vehicles add their Gears together, and both cars roll (Gear 2 + Gear\n3) five attack dice for their Smash Attacks. Neither car gets to roll Evades, as neither\ndeclared an Evade reaction. Red rolls five hits on Blue, and Blue rolls three hits back on\nRed. Both check off the lost Hull Points on their dashboards. Finally, both cars receive\ntwo Hazard Tokens for being in a road traffic accident. Red is now on 4 Hazard Tokens.\nWith no-one left to activate in Gear Phase 1, play proceeds to Gear Phase 2. Both\nRed and Blue are currently in Gear 2 (or higher), so both will get the chance to\nactivate this Gear Phase. Pole Position has moved to Red, so she moves the first vehicle.\nAs the Red car is beginning its activation in contact with the Blue car, it ignores Blue\nduring this Movement Step. Red selects the Medium Straight template again and puts it\ndown, ignoring Blue. The ever impetuous Red again rolls all three of her Skid Dice,\nhoping for a Slide and a Spin that could give her the movement to bring her front-\nmounted machine guns to bare on Blue. She rolls her dice and gets two Hazard results\nand a Spin. This isn\u2019t what she was looking for, so she decides to Push It. Whereby placing\nanother Hazard Token on her dashboard to pick up and reroll the two dice showing\nHazard Results. Disaster! They both come up Spins on the second roll! Red now has three\nSpin results and only one Shift result to cancel them out. She cannot Push It again and\nis already sitting on 5 Hazards Tokens. She can\u2019t avoid a Wipeout at this point.\nIn order to reduce the chance of Flipping during the Wipeout, Red decides to use\nher one Shift result to change down into Gear 2, taking her sixth hazard. She then\ngains the three hazards from her three Spins and moves into her Final Position at the\nend of the template. She resolves a desultory Spin once in her Final Position but it\u2019s not\ngoing to matter, she\u2019s on 8 hazards and suffers a Wipeout.\nFirst, she rolls her Flip check and gets a 5, so no Flip occurs. Next, she resets her current\nGear to 1 and discards all her Hazard Tokens. Finally, Blue spins Red\u2019s car on the spot to\nface in an unhelpful direction. Red isn\u2019t going to get another chance to activate this round,\nso it\u2019s over to Blue to see if she can use the temporary advantage to bring the heat on Red...."
    },
    {
        "page": "Page 62",
        "title": "In order to play a game of Gaslands, first build some teams to an agreed maximum",
        "text": "61\nIn order to play a game of Gaslands, first build some teams to an agreed maximum\nnumber of Cans, and then select (or roll for) the scenario. The scenario will tell\nyou how to set up the table, deploy your vehicles, and assign Pole Position.\nBUILDING A TEAM\nGaslands has a simple and flexible system for creating and customising teams. For\nyour first couple of games, we recommend you give each player a single car and a\nsingle buggy, both armed with a single front-facing machine gun. That will get\nyou up and running as you learn the basic mechanics of the game. Once you are\ncomfortable with the rules of the game, and want to create your own teams, turn\nto page 63 for the full rules for building custom teams.\nCHOOSING A SCENARIO\nEither play the Street Race scenario or turn to page 122 to select one of the many\nother Gaslands scenarios.\nSETTING UP\nA GAME"
    },
    {
        "page": "Page 63",
        "title": "STREET RACE",
        "text": "62\nSTREET RACE\nThe Street Race scenario is a simplified version of the Death Race scenario that\nappears on page 124. This scenario is intended as an introduction to the Gaslands\ngame, allowing new players to get to grips with the basic rules without adding\nanything extra. Once you are comfortable with the rules of Gaslands, we\nrecommend you play the proper Death Race scenario in place of this one, as that\nprovides a number of extra rules that make Gaslands racing more exciting.\nTEAMS\nGive each player a team of one Car and one Buggy, both armed with a front-\nmounted machine gun.\nSETUP\nSet up a pair of objects (flags or crates) a long straight apart to create a Starting\nLine and another pair to create a Finish Line. Make sure the start and finish line\nare at least three long straights away from each other. Lay out some terrain, such\nas rock, crates, or barriers to break up the route from the start line to the finish.\nPOLE POSITION\nRoll off to determine who has Pole Position. The player with Pole Position deploys\nthe first vehicle and activates the first vehicle. At the end of each Gear Phase, pass\nPole Position clockwise.\nSTARTING LINE\nStarting with the player in Pole Position, players take it in turns to place a vehicle\nanywhere touching the starting grid, not touching any other vehicle.\nVICTORY\nThe first vehicle to cross the Finish Line wins the race and the game is over. If\nthere is only one player with active vehicles in play at any point, the game ends\nand that player wins.\n62"
    },
    {
        "page": "Page 64",
        "title": "CREATING",
        "text": "CREATING\nA TEAM\nThe previous sections, \u201cBasic Rules\u201d and \u201cAdditional Rules\u201d, covered everything\nyou need to know to play a game of Gaslands. If you haven\u2019t played your first\ngame yet, you already know everything you need to go do that.\nAll of the rules beyond this point are optional, and will make more sense after\nyou have a couple of games under your belt to cement the core rules. These\noptional rules will be waiting for you, ready to make your Gaslands games more\nawesome by providing more customisation, more depth and more madcap ways\nto enjoy the game."
    },
    {
        "page": "Page 65",
        "title": "CUSTOMISING YOUR TEAM",
        "text": "64\nCUSTOMISING YOUR TEAM\nAfter your first couple of games, you will very likely want to start building your\nown personalised Gaslands teams. As you customise and maybe paint up your toy\ncars, Gaslands gives you quick and easy way to represent your own unique vehicles\non the tabletop.\nTEAM SIZE\nBefore each game, agree a team size with your fellow players. This is the total number\nof Cans you have available to build and equip all your vehicles. A good team size is\nbetween 25 and 100 Cans for each player.\n50 Cans each is generally agreed to be the \u201cstandard\u201d game size, which roughly\nbuys you two to four vehicles and a bit of kit, but this should not be considered a rule!\nCHOOSE A SPONSOR\nIf you are using sponsors (see page 91), select a sponsor for your team before you\nstart, which grants you a set of sponsored perks and determines which perk classes\nare available to you.\nBUILD VEHICLES\nEach player buys and customises vehicles up to the agreed team size. Building a\nvehicle is as simple as selected a vehicle type, arming it with weapons and upgrades\nup to its build slot limit, and personalising it further with perks from the sponsor\u2019s\npermitted perk classes."
    },
    {
        "page": "Page 66",
        "title": "BUILDING A VEHICLE",
        "text": "65\nBUILDING A VEHICLE\nTo build a new vehicle, follow these steps:\n\u2022\t Choose a vehicle type.\n\u2022\t Add weapons, noting the build slots required, and declaring a facing for\neach weapon.\n\u2022\t Add upgrades, noting the build slots required.\n\u2022\t Add perks from the permitted perk classes.\nCOST\nCans of gasoline are the new gold standard and are traded for parts and services\nthroughout the wasted Earth. Every vehicle, weapon, upgrade, and perk have an\nassociated cost. This cost is the number of Cans required to purchase the item\nwhen building your team.\nBUILD SLOTS\nEach vehicle has a number of Build Slots. When building a vehicle, weapons and\nupgrades require a number of available build slots to be fitted. Once weapons and\nupgrades have used up a vehicle\u2019s available build slots no more may be fitted\nFACING\nWhen arming a vehicle with a weapon, the player must declare a single facing for\nthat weapon. A weapon\u2019s facing determines the weapon\u2019s Arc of Fire.\nWhen you purchase a weapon or upgrade and declare the side-mounted\nfacing, you do not have to declare a specific side: the weapon or upgrade\ncounts as being mounted on both sides.\nPERKS\nVehicles may only purchase perks from those perks classes lists under their chosen\nsponsor. There is no limit to the number of perks each vehicle can have. Each\nperk may only be purchased once for each vehicle."
    },
    {
        "page": "Page 67",
        "title": "BASIC VEHICLE TYPES",
        "text": "66\nBASIC VEHICLE TYPES\nThese basic vehicle types describe the majority of the cars in your toy box. These\nvehicle types are intended to be quite broad brushes, and you can use each type\nto represent quite a wide array of makes and models. If you have a vehicle in front\nof you that doesn\u2019t fit any of these basic types, check out the Advanced Vehicle\nTypes section on page 68 for more options.\nBASIC VEHICLE TYPE TABLE\nVehicle Type\nWeight\nHull\nHandling\nMax Gear\nCrew\nBuild Slots\nSpecial Rules\nCost\nBuggy\nLightweight\n6\n4\n6\n2\n2\nRoll Cage.\n6\nCar\nMiddleweight\n10\n3\n5\n2\n2\n12\nPerformance Car\nMiddleweight\n8\n4\n6\n1\n2\nSlip Away.\n15\nTruck\nMiddleweight\n12\n2\n4\n3\n3\n15\nHeavy Truck\nHeavyweight\n14\n2\n3\n4\n5\n25\nBus\nHeavyweight\n16\n2\n3\n8\n3\n30\nBUGGY\nRoll Cage: When this vehicle suffers a fli , this vehicle may choose to ignore the\n2 hits received from the fli .\nPERFORMANCE CAR\nSlip Away: If this vehicle is targeted with a tailgate or T-Bone Smash Attack, and\nthis vehicle declares Evade as its reaction, this vehicle may perform a free activation\nimmediately after the active vehicle completes its activation.\nThis free activation does not count as the vehicle\u2019s activation this Gear Phase.\nUse of the Slip Away rule can allow this vehicle to activate twice in a row,\ntwice in one Gear Phase, or once in a Gear Phase that it does not qualify to\nactivate in (and it might then change Gear and qualify late in that phase).\nFriendly vehicles can trigger this effect."
    },
    {
        "page": "Page 68",
        "title": "BASIC WEAPONS",
        "text": "BASIC WEAPONS\nGaslands wouldn\u2019t be good television without guns! Here are the basic weapon\ntypes for you to use in your first few games. Once you are comfortable with the\nshooting rules, go ahead and dig into the Advanced Weapons rules on page 72 for\nmore deadly and explosive weaponry.\nWhen building a vehicle, weapons have two other statistics you need to know\nabout:\nBUILD SLOTS\nThe cost value determines the number of free build slots required to arm a vehicle\nwith this weapon.\nCOST\nThe cost value determines the cost in Cans of arming a vehicle with this weapon.\nBASIC WEAPON TABLE\nWeapon Name\nRange\nAttack Dice\nSpecial Rules\nBuild\nSlots\nCost\nHandgun\nMedium\n1D6\nCrew Fired.\n-\n-\nMachine Gun\nDouble\n2D6\n1\n2\nHeavy Machine Gun\nDouble\n3D6\n1\n3\nMinigun\nDouble\n4D6\n1\n5\nCrew Fired: A weapon that is Crew Fired benefits from a 360-degree Arc of Fire,\nand does not need to declare a facing when purchased."
    },
    {
        "page": "Page 69",
        "title": "ADVANCED",
        "text": "68\nADVANCED\nRULES\nAll the rules in this section are optional, but will provide a host of new and awesome\noptions to make your teams and your games more cinematic and explosive.\nADVANCED VEHICLE TYPES\nThe basic vehicle types are designed to cover the majority of conversions possible\nwith toy cars. However, enthusiastic rummagers in supermarket toy bins and\nthrift store crates may unearth delights that aren\u2019t covered by the existing basic\nvehicle types. The section provides an expanded set of vehicle types to allow you\nto include a broader range of vehicles in your games.\nADVANCED VEHICLE TYPES TABLE\nVehicle Type\nWeight\nHull\nHandling\nMax Gear\nCrew\nBuild Slots\nSpecial Rules\nCost\nDrag Racer\nLightweight\n4\n4\n6\n1\n2\nJet Engine.\n5\nBike\nLightweight\n4\n5\n6\n1\n1\nFull Throttle. Pivot.\n5\nBike with\nSidecar\nLightweight\n4\n5\n6\n2\n2\nFull Throttle. Pivot.\n8\nIce Cream Truck\nMiddleweight\n10\n2\n4\n2\n2\nInfuriating Jingle.\n8\nGyrocopter\nMiddleweight\n4\n4\n6\n1\n0\nAirwolf. Airborne.\n10\nAmbulance\nMiddleweight\n12\n2\n5\n3\n3\nUppers. Downers.\n20\nMonster Truck\nHeavyweight\n10\n3\n4\n2\n2\nAll Terrain. Up and Over.\n25\nHelicopter\nHeavyweight\n8\n3\n4\n3\n4\nAirwolf. Airborne. Restricted\n30\nTank\nHeavyweight\n20\n4\n3\n3\n4\nPivot. Up and Over. All Terrain.\nTurret. Restricted\n40\nWar Rig\nHeavyweight\n26\n2\n4\n5\n5\nSee War Rig rules.\n40"
    },
    {
        "page": "Page 70",
        "title": "You will find a blank dashboard card in the back of this book. Fill it in with the",
        "text": "69\nYou will find a blank dashboard card in the back of this book. Fill it in with the\nstats of the vehicle you have chosen. You can also find a full set of vehicle\ndashboards to download on the Gaslands website.\nRESTRICTED VEHICLE TYPES\nSome vehicle types are Restricted. If you are playing with Sponsor rules\n(see page 91), Helicopters and Tanks cannot be purchased as standard.\nOnly teams with an appropriate Sponsor perk may purchase those vehicle\ntypes, (see Sponsors, page 91).\nWhilst Helicopters and Tanks are restricted in games that use Sponsors,\nyou can of course ignore this restriction if you like, and play with the full set of\nvehicle types. Your table, your rules.\nAMBULANCE\nUPPERS\nIf this vehicle is involved in a Collision in which both vehicles declare an\nEvade, both vehicles must declare a single change Gear up immediately after\nthe Collision is resolved (gaining a Hazard Token as normal). If either vehicle\nis already at its max Gear, the change of Gear does not affect that vehicle\u2019s\ncurrent Gear, but that vehicle does gain a Hazard Token.\nDOWNERS\nWhen this vehicle is involved in a Collision during its activation in which it\ndeclares a Smash Attack, the target vehicle does not gain any Hazard Tokens from\nthe Collision and instead discards 2 Hazard Tokens.  Then reduce the target\nvehicle\u2019s Crew Value by 1 until the end of the Gear Phase.\nBIKE AND BIKE WITH SIDECAR\nFULL THROTTLE\nThis vehicle considers the Long Straight movement template to be permitted in any\nGear. The Long Straight is not considered either Hazardous or Trivial in any Gear.\nPIVOT\nAt the start of this vehicle\u2019s activation, if this vehicle\u2019s current Gear is 1, this\nvehicle may make a pivot about its centre to face any direction. This pivot cannot\ncause a Collision and cannot leave this vehicle touching an obstruction."
    },
    {
        "page": "Page 71",
        "title": "DRAG RACER",
        "text": "70\nDRAG RACER\nJET ENGINE\nA vehicle with a jet engine counts as having a Nitro Booster with infinite ammo\ntokens. This means this vehicle automatically Explodes when it is Wrecked. A\nvehicle with a jet engine must use Nitro Booster every time it activates.\nHELICOPTER AND GYROCOPTER\nAIRBORNE\nThis vehicle ignores non-tall obstructions, dropped weapons, and terrain at all\ntimes, except when checking for Cover, and when targeting other vehicles in its\nAttack Step.\nOther vehicles ignore this vehicle at all times, except that other vehicles may\ntarget this vehicle during their Attack Steps. This vehicle cannot be involved in\nCollisions.\nAIRWOLF\nAt the start of this vehicle\u2019s activation, this vehicle may gain 2 Hazard Tokens to\nmake a single pivot about its centre point, up to 90 degrees.\nBOMBS AWAY\nWhen purchasing weapons for this vehicle, this vehicle may count dropped\nweapons as requiring 0 build slots. This vehicle may attack with any number of\ndropped weapons in a single Attack Step.\nICE CREAM TRUCK\nINFURIATING JINGLE\nVehicles that target this vehicle with a Smash Attack during a\nCollision gain no Hazard Tokens during step 6 of the Collision\nresolution.\n\u00a9 James Hall"
    },
    {
        "page": "Page 72",
        "title": "MONSTER TRUCK",
        "text": "71\nMONSTER TRUCK\nALL TERRAIN\nThis vehicle may ignore the penalties for rough and treacherous surfaces.\nUP AND OVER\nDuring this vehicle\u2019s Movement Step, after resolving a Collision with an\nobstruction of a lower weight class, this vehicle may declare that it is going \u201cUp\nand Over\u201d. If it does, it may ignore the obstruction for the remainder of its\nMovement Step, as it drives right over the top of it. This vehicle cannot use this\nability to ignore another vehicle with the Up and Over special rule.\nTANK\nALL TERRAIN\nThis vehicle may ignore the penalties for rough and treacherous surfaces.\nPIVOT\nAt the start of this vehicle\u2019s activation, if this vehicle\u2019s current Gear is 1, this\nvehicle may make a pivot about its centre to face any direction. This pivot cannot\ncause a Collision and cannot leave this vehicle touching an obstruction.\nTURRET\nThis vehicle may count one weapon as turret-mounted without paying for the\nupgrade.\nUP AND OVER\nDuring this vehicle\u2019s Movement Step, after resolving a Collision with an\nobstruction of a lower weight class, this vehicle may declare that it is going \u201cUp\nand Over\u201d. If it does, it may ignore the obstruction for the remainder of its\nMovement Step, as it drives right over the top of it. This vehicle cannot use this\nability to ignore another vehicle with the \u201cUp and Over\u201d special rule.\nWAR RIG\nThe War Rig has multiple special rules. See the War Rig section on page 116 for\ndetails."
    },
    {
        "page": "Page 73",
        "title": "ADVANCED WEAPONS",
        "text": "72\nADVANCED WEAPONS\nIn this section, you will find a bountiful armoury of implements of carnage, from\nthe explosive to the exotic.\nADVANCED WEAPON TABLE\nWeapon Name\nRange\nAttack Dice\nSpecial Rules\nBuild\nSlots\nCost\n125mm Cannon\nDouble\n8D6\nAmmo 3. Blast. See special rules.\n3\n6\nArc Lightning\nProjector\nDouble\n6D6\nAmmo 1. Electrical. See special rules.\n2\n6**\nBazooka\nDouble\n3D6\nAmmo 3. Blast.\n2\n4\nBFG\nDouble\n10D6\nAmmo 1. See special rules.\n3\n1\nCombat Laser\nDouble\n3D6\nSplash. See special rules.\n1\n5\nDeath Ray\nDouble\n3D6\nAmmo 1. Electrical. See special rules.\n1\n3\nFlamethrower\nLarge Burst\n6D6\nAmmo 3. Splash. Fire. Indirect.\n2\n4\nGrabber Arm\nShort\n3D6\nSee special rules.\n1\n6\nGrav Gun\nDouble\n(3D6)\nAmmo 1. Electrical. See special rules.\n1\n2**\nHarpoon\nDouble\n(5D6)\nSee special rules.\n1\n2\nKinetic Super\nBooster\nDouble\n(6D6)\nAmmo 1. Electrical. See special rules.\n2\n6**\nMagnetic Jammer\nDouble\n-\nElectrical. See special rules.\n-\n2**\nMortar\nDouble\n4D6\nAmmo 3. Indirect.\n1\n4\nRockets\nDouble\n6D6\nAmmo 3.\n2\n5\nThumper\nMedium\n-\nAmmo 1. Electrical. Indirect.\n360-degree. See special rules.\n2\n4**\nWall of Amplifiers\nMedium\n-\n360-degree arc of fire. See special\nrules.\n3\n4\nWreck Lobber\nDouble/\nDropped\n-\nAmmo 3. See special rules.\n4\n4\nWrecking Ball\nShort\n*\n*See special rules.\n3\n2\n** Mishkin-sponsored teams only.\n125MM CANNON\nA tank gun is a ridiculous weapon for a civilian vehicle to carry. When fi ed, the\nactive vehicle immediately gains 2 Hazard Tokens if it is not a Tank."
    },
    {
        "page": "Page 74",
        "title": "ARC LIGHTNING PROJECTOR",
        "text": "ARC LIGHTNING PROJECTOR\nMishkin-sponsored teams only. The Arc Lightning Projector is a dangerous\nweapon that can arc electricity across multiple conductive targets. After damaging\na target, this vehicle must immediately attack another target within Short range\nand 360-degree Arc of Fire of the current target (including this vehicle). This\nchain-reaction continues until the weapon fails to damage a target, or there are no\nfurther viable targets. This vehicle can target friendly vehicles with the Arc\nLightning Projector. This vehicle cannot target the same vehicle twice in a single\nAttack Step with the Arc Lightning Projector.\nBFG\nWhen this weapon is fi ed, the vehicle makes an immediately forced move\nmedium straight backwards, reduced to Gear 1 and gains 3 Hazard Tokens. Front\nmounted only.\nDEATH RAY\nMishkin-sponsored teams only. If this weapon scores fi e or more un-cancelled\nhits on the target during a single attack, instead of causing damage, the target car\nis immediately removed from play (although it counts as having been Wrecked\nfor the purposes of Audience Votes, scenario rules, etc.).\nGRABBER ARM\nIf this vehicle attacks a target vehicle of the same weight class or lighter with the\nGrabber Arm and scores one or more un-cancelled hits, the controller of the\nactive vehicle may place the target vehicle anywhere within Short range of the\ntarget vehicle\u2019s original position. The target vehicle may be pivoted to face any\ndirection. This movement causes a Collision Window.\nGRAV GUN\nMishkin-sponsored teams only. If this weapon scores one or more un-cancelled\nhits on the target, instead of causing damage the attacking vehicle\u2019s controller\nmust choose one of the following: until the end of the target\u2019s next activation the\ntarget counts as one weight class heavier or until the end of the target\u2019s next\nactivation the target counts as one weight class lighter.\n\u00a9 Jake Zettelmaier"
    },
    {
        "page": "Page 75",
        "title": "HARPOON",
        "text": "74\nHARPOON\nThis weapon\u2019s hits do not cause damage. Instead, the first un-cancelled hit on the\ntarget spins the target vehicle on the spot to either face directly away from or\ndirectly towards the attacking vehicle, whichever requires the smallest degree of\nrotation, as the harpoon catches and the chain goes taut. This triggers a Collision\nWindow.\nThe second and subsequent un-cancelled hits on the target then each cause\nthe target to make a forced Short Straight move towards the attacker, as the\nharpoon reels the target in.\nIf the target is a heavier weight class than the attacker, it is the attacking\nvehicle that is spun and moved towards the target vehicle instead.\nKINETIC SUPER BOOSTER\nMishkin-sponsored teams only. The Kinetic Super Booster is a bizarre electrical\nweapon that transfers a jolt of kinetic energy to the target. The target of a Super\nBooster attack suffers no damage, but instead immediately increases its current\nGear by one for every successful hit, without gaining Hazard Tokens. The Super\nBooster may not increase a vehicle\u2019s current Gear beyond its max Gear.\nMAGNETIC JAMMER\nMishkin-sponsored teams only. The target vehicle may not discard ammo tokens\nduring its next activation.\nTHUMPER\nMishkin-sponsored teams only. This weapon does not need to declare a facing\nwhen purchased.\nThe Thumper is a powerful sonic device that emits a shock wave that hurls\nnearby vehicles into the air. When this vehicle declares an attack with the\nThumper, every other vehicle (friend or foe) within Medium range of this vehicle\nin a 360-degree Arc of Fire immediately makes a Flip check, in which they count\ntheir current Gear as 2 higher, up to a maximum of 6.\nWALL OF AMPLIFIERS\nThis weapon does not require a target. When fi ed, this weapon automatically\ncauses one hit to every vehicle within Medium range and within a 360-degree\nArc of Fire. These hits do not cause damage and may be Evaded. For each un-\ncancelled hit on a vehicle, choose one: either discard 1 Hazard Token from the\nvehicle or add 1 Hazard Token to the vehicle."
    },
    {
        "page": "Page 76",
        "title": "WRECK LOBBER",
        "text": "75\nWRECK LOBBER\nIt was inevitable that someone would invent a gun that shoots cars instead of\nbullets.\nTrebuchet: The Wreck Lobber does not require a target. When it is fi ed,\nplace a marker the size of a penny within Double range of the Wreck Lobber\u2019s fi e\narc. Roll a Skid Die.\n\u2022\t On a Shift result: place the wreck of a Car touching the marker and trigger\na Collision Window.\n\u2022\t On a Spin or Slide result: the player to the left of the active player must\nplace the wreck anywhere within Short range of the marker and trigger a\nCollision Window.\n\u2022\t On a Hazard Result: the player to the left of the active player must place\nthe wreck touching the active vehicle and trigger a Collision Window.\nLow-loader: If this vehicle collides with a wreck, it may gain 1 Ammo Token\nfor the Wreck Lobber.\nDumper: This vehicle may fi e the Wreck Lobber as a rear-mounted dropped\nweapon instead of using the Trebuchet rules above. In this case, the wreck of a car\nis placed touching the rear of the active vehicle, and no Collision Window is\ntriggered."
    },
    {
        "page": "Page 77",
        "title": "WRECKING BALL",
        "text": "76\nWRECKING BALL\nThis weapon does not require a target. When fi ed, this vehicle must immediately\nengage in a T-Bone Collision with every vehicle and Destructible obstacle within\nShort range of it, in a 360-degree Arc of Fire, in an order chosen by this vehicle\u2019s\ncontroller.\nDuring these Collisions, all vehicles involved count as having no weapons or\nperks except this one and all other vehicles must declare an Evade reaction. During\neach these Collisions this vehicle gains 2 Smash Attack dice. This vehicle does not\ngain Hazard Tokens during these Collisions. Collisions triggered by the Wrecking\nBall do not benefit f om effects from upgrades, such as Rams or Exploding Rams.\nCREW FIRED WEAPONS\nThe wild-eyed crews of Gaslands vehicles sport a deadly array of hand-held day-\nruiners.\nCREW FIRED WEAPONS TABLE\nWeapon Name\nRange\nAttack\nDice\nSpecial Rules\nBuild\nSlots\nCost\nBlunderbuss\nSmall\nBurst\n2D6\nCrew Fired. Splash.\n-\n2\nGas Grenades\nMedium\n(1D6)\nAmmo 5. Crew Fired. Indirect. Blitz. See\nspecial rules.\n-\n1\nGrenades\nMedium\n1D6\nAmmo 5. Crew Fired. Blast. Indirect.\nBlitz.\n-\n1\nMagnum\nDouble\n1D6\nCrew Fired. Blast.\n-\n3\nMolotov Cocktails\nMedium\n1D6\nAmmo 5. Crew Fired. Fire. Indirect.\nBlitz.\n-\n1\nShotgun\nLong\n*\nCrew Fired. See special rules.\n-\n4\nSteel Nets\nShort\n(3D6)\nCrew Fired. Blast. See special rules.\n-\n2\nSubmachine Gun\nMedium\n3D6\nCrew fired.\n-\n5\nCREW FIRED\nA weapon that is Crew Fired benefits from a 360-degree Arc of Fire and does not\nneed to declare a facing when purchased.\nGAS GRENADES\nIf this weapon scores one or more un-cancelled hits on the target, instead of\ncausing damage, reduce the target\u2019s Crew Value by 1 for each un-cancelled hit, to\na minimum of 0, until the end of the Gear Phase."
    },
    {
        "page": "Page 78",
        "title": "STEEL NETS",
        "text": "77\nSTEEL NETS\nThis weapon\u2019s hits do not cause damage. Hits will add Hazard Tokens as a result\nof the Blast special rule as normal.\nSHOTGUN\nWhen attacking with this weapon, roll 3D6 attack dice if the target is within\nShort range, 2D6 attack dice if the target is within Medium range, and 1D6\nattack dice if the target is within Long range.\nDROPPED WEAPONS\nYou are at the front of the pack. The road is empty ahead of you. Worry not,\nhere\u2019s a toolkit of unpleasant things you can do to anyone that gets up too close\nbehind.\nDROPPED WEAPONS TABLE\nWeapon Name\nRange\nAttack\nDice\nSpecial Rules\nBuild\nSlots\nCost\nCaltrop Dropper\nDropped\n2D6\nAmmo 3. Small Burst. See special rules.\n1\n1\nGlue Dropper\nDropped\n-\nAmmo 1. See special rules.\n1\n1\nMine Dropper\nDropped\n4D6\nAmmo 3. Small Burst. Blast. See special\nrules.\n1\n1\nNapalm Dropper\nDropped\n4D6\nAmmo 3. Small Burst. Fire. See special\nrules.\n1\n1\nOil Slick Dropper\nDropped\n-\nAmmo 3. See special rules.\n-\n2\nRC Car Bombs\nDropped\n4D6\nAmmo 3. See special rules.\n-\n3\nSentry Gun\nDropped\n2D6\nAmmo 3. See special rules.\n-\n3\nSmoke Dropper\nDropped\n-\nAmmo 3. See special rules.\n-\n1"
    },
    {
        "page": "Page 79",
        "title": "DROPPED WEAPON RULES",
        "text": "78\nDROPPED WEAPON RULES\nDropped weapons may not be front-mounted. A vehicle may only attack with a\nsingle dropped weapon in a single Attack Step.\nTo attack with a dropped weapon: place the appropriate shooting template\nwithin the weapon\u2019s Arc of Fire, and instead of rolling to attack, leave it on the\ntable until instructed otherwise. This dropped weapon template does not count\nas overlapping the active vehicle.\nLeave the dropped weapon template in place when the vehicle next moves.\nThe dropped weapon template remains in play for the rest of the game, unless\ntheir specific ules state otherwise.\nIf a dropped weapon template overlaps a vehicle, or if a vehicle\u2019s movement\ntemplate or Final Position overlaps a dropped weapon template, resolve the\ndropped weapon\u2019s effects against that vehicle in the next Collision Window.\nVehicles attacked by a dropped weapon may Evade any hits from that weapon.\nIf there are multiple dropped weapon templates stacked on top of each other,\njust resolve each template in order, from the top of the stack to the bottom."
    },
    {
        "page": "Page 80",
        "title": "CALTROP DROPPER",
        "text": "79\nCALTROP DROPPER\nThe dropped weapon template for this dropped weapon counts as a treacherous\nsurface, (see Terrain, page 86).\nThe first vehicle affected by this weapon is attacked with a 2D6 attack, then\nremove the Caltrops template from play.\nGLUE DROPPER\nThe dropped weapon template for the Glue Dropper counts as a treacherous\nsurface. Any vehicle affected by this weapon must reduce its current Gear by 2 at\nthe end of their Movement Step. A single vehicle may not be affected by this\nweapon two activations in a row.\nMINE DROPPER\nThe first vehicle affected by this weapon is attacked with a 4D6 attack with Blast,\nthen remove the Mine\u2019s template from play.\nNAPALM DROPPER\nThe first vehicle affected by this weapon is attacked with a 4D6 attack with Fire,\nthen remove the Napalm template from play.\nOIL SLICK DROPPER\nThe dropped weapon template for the Oil Slick Dropper counts as a treacherous\nsurface, (see Terrain, page 86).\nRC CAR BOMBS\nBombs are taped to remote-controlled cars, which are dropped from a vehicle and\nthen piloted to impact.\nWhen attacking with this dropped weapon, place a RC Car (use a tiny car\nminiature, no larger than 20mm square) so that it is within Short range of the\nattacking vehicle, and facing in any direction. This placement triggers a Collision\nWindow.\nThe RC Car counts as a lightweight vehicle in current Gear 3 with 1 Hull\nPoint, 1 Crew and 0 Handling. This tiny car can make shooting attacks but\ncannot change Gear. Although controlled by the player that dropped it, the RC\nCar does not count as part of the player\u2019s team, and so cannot be used for the\npurposes of scenario rules, Audience Votes, or perks.\nThe RC Car is involved in a Collision, it suffers one damage before the Collision\nis resolved. When the RC Car would be Wrecked, it instead explodes. When the\nRC Car explodes, it rolls 4D6 attack dice, as if it were a middleweight vehicle.\nIf the RC Car wipes out, it suffers one damage before the Wipeout is resolved."
    },
    {
        "page": "Page 81",
        "title": "SENTRY GUN",
        "text": "SENTRY GUN\nWhen attacking with this dropped weapon, place a Sentry Gun so that it is within\nShort range of the attacking vehicle.\nThe Sentry Gun remains in play as a lightweight destructible obstacle. They\nmay be targeted with shooting attacks and have 2 Hull Points.\nThis Sentry Gun automatically makes a 2D6 shooting attack against any\nvehicle that ends their Movement Step within Medium range of the Sentry Gun\nin a 360-degree Arc of Fire. The target may Evade as normal. This Sentry Gun\nwill never target vehicles from the team of the vehicle that dropped it.\nAlthough controlled by the player that dropped it, the Sentry Gun does not\ncount as part of the player\u2019s team, and so cannot be used for the purposes of\nscenario rules, Audience Votes, or perks.\nSMOKE DROPPER\nThis dropped weapon template counts as an obstruction for the purposes of\ndetermining Cover.\nWhilst a vehicle is in contact with this dropped weapon template, that vehicle\ncounts as distracted.\nIf any part of a vehicle\u2019s movement template or Final Position touches this\ndropped weapon template, the vehicle gains 1 Hazard Token at the end of its\nMovement Step.\nWEAPON SPECIAL RULES\nATTACKING WITH SPECIAL WEAPONS\nSome weapons have special rules that trigger only if the weapon hits or\ndamages the target. When rolling to attack, a player will need to make it clear\nwhich dice represent attacks from which weapons, if special rules would\napply to those attacks. You might consider using different coloured dice for\nthose special attacks, or rolling them to one side.\n\u00a9 Jake Zettelmaier"
    },
    {
        "page": "Page 82",
        "title": "AMMO",
        "text": "81\nAMMO\nSome weapons and upgrades have limited fuel or ammunition. A weapon or\nupgrade with this special rule begins the game with (x) number of Ammo Tokens\non its dashboard for that weapon or upgrade, where (x) is the value listed.\nBefore making an attack with this weapon or using this upgrade, this vehicle\nmust discard an Ammo Token from this weapon or upgrade. If the vehicle cannot\ndiscard an Ammo Token, this weapon or upgrade may not be used.\nAmmo Tokens are specific to a given weapon or upgrade. A vehicle may not\ndiscard Ammo Tokens from one weapon or upgrade to attack with another\nweapon or use another upgrade.\nf you are playing with Audience Votes, you can use Reload to replenish your\nAmmo Tokens. See page 89 for more information.\nBLAST\nFor every un-cancelled hit caused by a weapon or effect with the Blast rule, the\ntarget immediately gains 1 Hazard Token.\nBLITZ\nThis vehicle counts as being armed with a number of copies of this weapon equal\nto this weapon\u2019s remaining Ammo Tokens, where each copy counts as having a\nsingle Ammo Token. This means that during its Attack Step, this vehicle may attack\nwith this weapon any number of times, as long as it doesn\u2019t attack more times that\nis has Ammo Tokens, and doesn\u2019t attack more times than its Crew Value.\nCREW FIRED\nA weapon that is Crew Fired benefits from a 360-degre Arc of Fire and does not\nneed to declare a facing when purchased.\nFIRE\nIf a vehicle suffers at least one damage from a weapon or effect with the Fire\nspecial rule, it gains the On-Fire rule in addition to suffering damage. A vehicle\ncannot gain the On-Fire rule a second time.\nOn Fire: At the start of this vehicle\u2019s activation, it loses 1 Hull Point. This\nvehicle\u2019s Smash Attacks count as having the Fire special rule. If this vehicle ever\nhas zero Hazard Tokens, the fi e goes out and this vehicle loses the On-Fire rule."
    },
    {
        "page": "Page 83",
        "title": "INDIRECT",
        "text": "82\nINDIRECT\nWhen making a shooting attack with a weapon with this special rule, the vehicle\nmay ignore Terrain and Cover during that attack.\nSPLASH\nWhen a weapon with the Splash rule is used to attack, the weapon must target,\nand attack, every vehicle beneath the shooting template, including friendly\nvehicles. Each target must suffer a separate attack from the weapon.\nFor example, a truck has a side-mounted Flamethrower and is driving besides two\nenemy cars. The player declares an attack against one of the two cars. He takes the\nLarge Burst template and places it perpendicular with the side of his truck, and\ntouching the side edge of his truck. He is able to catch both enemy cars under the\ntemplate and so rolls two separate attacks, one against each enemy, with the full 6D6\nattack dice against both.\nZERO CREW\nSome game effect can reduce a vehicle\u2019s Crew Value. When a vehicle with zero\nCrew is selected to activate, it first automatically changes down one Gear to a\nminimum of Gear 1. During its Movement Step, only movement templates that\nare hazardous in the vehicle\u2019s current Gear count as permitted. This means in\nGear Phases 1 and 2, the player controlling a vehicle will be forced to select\nmovement templates that are not permitted."
    },
    {
        "page": "Page 84",
        "title": "VEHICLE UPGRADES",
        "text": "83\nVEHICLE UPGRADES\nNo mechanic that builds vehicles for Gaslands can resist adding a few personal\ntouches.\nVEHICLE UPGRADE TABLE\nUpgrades\nSpecial Rules\nBuild Slots\nCost\nArmour Plating\n+2 Hull Points\n1\n4\nExperimental Nuclear Engine\nElectrical. See special rules.\n-\n5**\nExperimental Teleporter\nElectrical. See special rules.\n-\n7**\nExploding Ram\nAmmo 1. See special rules.\n-\n3\nExtra Crewmember\n+1 Crew, up to a maximum of twice the vehicle\u2019s starting Crew Value\n-\n4\nImprovised Sludge Thrower\nSee special rules.\n1\n2\nNitro Booster\nAmmo 1. See special rules.\n-\n6\nRam\nSee special rules.\n1\n4\nRoll Cage\nSee special rules.\n1\n4\nTank Tracks\n-1 Max Gear. +1 Handling. See special rules.\n1\n4\nTurret Mounting for Weapon\nWeapon gains 360 arc of fire.\n-\n(x3)\n** Mishkin-sponsored teams only.\nARMOUR PLATING\nThe vehicle has been loaded with additional plates and shielding. This vehicle has\nits Hull Value permanently increased by 2. A single vehicle may be fitted with\nmultiple Armour Plating upgrades for further +2 hull each time.\nEXPERIMENTAL NUCLEAR ENGINE\nMishkin-sponsored teams only. This upgrade may not be purchased for\nlightweight vehicles. A vehicle may only purchase this upgrade once.\nAdd 2 to this vehicle\u2019s max Gear, (up to a maximum of 6). This vehicle\nconsiders the Long Straight movement to be permitted in any Gear. The Long\nStraight is not considered either Hazardous or Trivial in any Gear.\nIf this vehicle ever fails a Flip check, it is immediately Wrecked and\nautomatically Explodes. When this vehicle Explodes, it counts as Heavyweight.\nEXPERIMENTAL TELEPORTER\nMishkin-sponsored teams only. A vehicle may only purchase this upgrade once.\nAt the start of this vehicle\u2019s activation this vehicle may choose to activate the\nExperimental Teleporter prior to (and in addition to) its normal Movement Step."
    },
    {
        "page": "Page 85",
        "title": "When the Experimental Teleporter is activated, this vehicle gains 3 Hazard",
        "text": "84\nWhen the Experimental Teleporter is activated, this vehicle gains 3 Hazard\nTokens, and then rolls a single Skid Die.\nIf the Skid Dice result is any result other than a Hazard, place this vehicle\nanywhere within Medium range of its current position, not touching an obstruction\nor terrain, without altering the vehicle\u2019s facing. This does not cause a Collision. This\nvehicle then begins its normal Movement Step from this new location.\nIf the Skid Dice result is a Hazard, the player to the left of the controller of the\nvehicle places this vehicle anywhere within Long range of its current position,\nnot touching an obstruction or terrain, without altering its facing. This does not\ncause a Collision.\nEXPLODING RAM\nWhen purchasing this upgrade, a facing must be declared for it, as if it was a\nweapon. A vehicle may only purchase this upgrade once. Lightweight vehicles\nmay not purchase this weapon.\nThe first time this vehicle is involved in a Collision on the declared facing in\na game, this vehicle must declare a Smash Attack (even if the Collision is a\nTailgate). During this Smash Attack this vehicle gains +6 attack dice. If any 1s or\n2s are rolled on this vehicle\u2019s attack dice during this Smash Attack, this vehicle\nimmediately loses one hull point for each 1 or 2 rolled.\nA vehicle may equip both a Ram and an Explosive Ram on the same facing,\nand their effects are cumulative.\nEXTRA CREWMEMBER\nEach Extra Crewmember purchased increases the vehicles Crew Value by 1. This\nwill increase the number of attacks a vehicle can make in its Attack Step. See\nShooting Attacks, page 30.\nA vehicle may not purchase more Extra Crewmembers than its starting Crew\nValue.\nFor example, a pickup truck, which has a Crew Value of 3, may purchase up to 3\nExtra Crewmembers, for a maximum Crew Value of 6.\nIMPROVISED SLUDGE THROWER\nThis vehicle may place the Burst templates for its dropped weapons anywhere\nthat is at least partially within Medium range and 360-degree Arc of Fire of this\nvehicle.\nNITRO BOOSTER\nOnce per activation, at the start of a Movement Step, this vehicle may declare\nthat it is using a Nitro Booster. If it does, this vehicle makes an immediate forced,\nLong Straight move forward, and then gains Hazard Tokens until it has 5 Hazard\nTokens. It then resolves its Movement Step as normal, except that the vehicle may"
    },
    {
        "page": "Page 86",
        "title": "not reverse. At the end of a Movement Step in which this vehicle used Nitro",
        "text": "85\nnot reverse. At the end of a Movement Step in which this vehicle used Nitro\nBooster, it gains Hazard Tokens until it has 5 Hazard Tokens.\nRAM\nThe Ram can represent a ram, a bulldozer blade, a cow-catcher, a buzz saw, a\nwrecking ball on a chain, spiked or scythed wheels, metal spikes, or any other\nvicious or dangerous close combat weapon attached to the vehicle.\nWhen purchasing this upgrade, a facing must be declared for it, as if it was a\nweapon. A vehicle may only purchase a single Ram on each facing.\nWhen involved in a Collision on the declared facing, this vehicle may add 2\nattack dice to its Smash Attack, and this vehicle does not gain any Hazard Tokens\nas a result of the Collision.\nROLL CAGE\nWhen this vehicle suffers a Flip, this vehicle may choose to ignore the 2 hits\nreceived from the Flip.\nTANK TRACKS\nThe vehicle with Tank Tracks has had its wheels replaced with caterpillar tracks.\nThis increases its handling by 1, but reduces its max Gear by 1. This vehicle may\nalso ignore rough and treacherous surfaces.\nA vehicle may only purchase this upgrade once. Tanks, Helicopters, and\nGyrocopters may not purchase Tank Tracks.\nTURRET MOUNTING FOR WEAPON\nWhen purchasing a shooting weapon for a vehicle, players may pay three times\nthe basic cost of the weapon to make it Turret-mounted. A Turret-mounted\nweapon has a 360-degree Arc of Fire (see Arc of Fire, page 28).\nFor example, a front-mounted Minigun will cost you 5 Cans, but a Turret-\nmounted Minigun will cost you 15 Cans."
    },
    {
        "page": "Page 87",
        "title": "TERRAIN",
        "text": "86\nTERRAIN\nA great looking selection of terrain, scenery, and obstructions will improve your\nGaslands games. Here are some additional effects that you can choose to use to\ngive your games more variety and challenge.\nSURFACES\nSurfaces are types of terrain that describe the condition of the ground. Surfaces\ndo not count as obstructions.\nROAD\nIf every part of a vehicle\u2019s movement template and Final Position (after resolving\nall Skid Dice) overlaps a Road Surface, then the vehicle may discard a Hazard\nToken at the end of this Movement Step.\nROUGH\nIf any part of a vehicle\u2019s movement template or Final Position (after resolving all\nSkid Dice) overlaps a Rough Surface, the vehicle gains 1 Hazard Token at the end\nof its Movement Step.\nTREACHEROUS\nIf any part of a vehicle\u2019s movement template or Final Position (after resolving all\nSkid Dice) overlaps a Treacherous Surface, the vehicle gains 2 Hazard Tokens at\nthe end of its Movement Step."
    },
    {
        "page": "Page 88",
        "title": "EDGE OF THE TABLE",
        "text": "87\nEDGE OF THE TABLE\nIf any part of a vehicle\u2019s movement template (after resolving all Skid Dice) overlaps\nthe edge of the play area, the vehicle is disqualified and removed from play, (unless\nthe scenario specifiesotherwise). A disqualifiedvehicle does not count as Wrecked.\nOBSTACLES\nObstacles always count as obstructions.\nObstacles have a weight, as vehicles do. Heavyweight obstacles are solid\nimmovable features, such as walls, buildings, and rocks. Middleweight obstacles are\nless substantial features, such as oil barrels, crash barriers, and lampposts. Lightweight\nobstacles are, presumably, fruit stalls or workmen carrying sheets of glass.\nTALL\nObstacles may be Tall. If the shooting template overlaps a Tall obstruction before\nit touches the target, the target cannot be targeted by this weapon. Agree with\nyour fellow players at the start of the game which obstacles are Tall.\nDESTRUCTIBLE OBSTACLES\nObstacles may be Destructible. Agree with your fellow players at the start of the\ngame which obstacles are Destructible.\nIf a vehicle collides with a Destructible obstacle, remove the obstacle from\nplay immediately after resolving the Collision.\nVOLATILE OBSTACLES\nObstacles, such as gas canisters or ammo dumps, may be Volatile. Agree with\nyour fellow players at the start of the game which obstacles are Volatile.\nWhen a vehicle collides with a Volatile obstacle, roll a die before declaring\nreactions. On the roll of a 4+, the Volatile obstacle explodes! Make an attack with\nBlast rule against each vehicle within Medium range of the exploding volatile\nobstacle, calculating attack dice based on the weight of the obstacle, as if it was an\nexploding wreck, then remove the obstacle. See Explosions, page 44.\nRAMPS\nAgree which terrain items count as a Ramp with your fellow players before the\ngame. Nominate an \u201centry edge\u201d for the Ramp, which is the bit of the ramp that\nyou drive up on to.\nIf a vehicle\u2019s movement template or Final Position overlaps any edge other\nthan the entry edge, they stop at the edge of the Ramp and roll a D6. If the die\nroll is equal to or under the vehicle\u2019s current Gear: make a Jump, else make a\nTumble."
    },
    {
        "page": "Page 89",
        "title": "JUMP",
        "text": "88\nJUMP\nThe vehicle stops at the edge of the Ramp and then makes an immediate forced\nmove Medium Straight directly forward if in current Gear 1 to 4, or long Straight\nForwards if in current Gear 5 or 6, during which it ignores all terrain and other\nvehicles. This movement causes a Collision Window. This vehicle then gains 2\nHazard Tokens and 1 Audience Vote.\nTUMBLE\nThe vehicle stops at the edge of the Ramp and then makes an immediate\nadditional forced move Short Straight forward, during which it ignores all terrain\nand other vehicles. This movement causes a Collision Window. This vehicle then\nsuffers a 4D6 attack and gains +6 Hazard Tokens.\nIf, by ignoring obstructions during a Jump or Tumble, this vehicle\u2019s Final\nPosition would overlap an obstruction, move this vehicle backwards along the\nmovement template by the minimum amount to avoid overlapping any obstruction.\nAUDIENCE VOTES\nGaslands is a televised death-sport and the organisers want to ensure that the\naudience stays on the edge of their seats. In recent years, the producers have\nstarted to introduce ways for the viewers at home to participate in the carnage.\nThis is represented by Audience Votes.\nAs you\u2019ll see, Audience Votes are used as a positive in-game handicap system,\nto allow players to get back into the game or to cause general mayhem.\nGAINING AUDIENCE VOTES\nPlayers gain Audience Votes when certain conditions are met. The player, not any\nspecific vehicle, gains Audience Votes. A player may have any number of Audience\nVotes.\nAUDIENCE VOTES TABLE\nCondition\nAudience Votes\nA player has one of their vehicles Wrecked\nGain 1 Audience Vote\nA player starts a round without any active vehicles\nGain 2 Audience Votes\nEach Sponsor also provides teams with additional conditions to gain Audience\nVotes which reward actions that that sponsor\u2019s fans want to see on their TV, as do\nsome scenarios."
    },
    {
        "page": "Page 90",
        "title": "Use tokens, dice, gems, or bottle caps to track of how many Audience Votes",
        "text": "89\nUse tokens, dice, gems, or bottle caps to track of how many Audience Votes\neach player has.\nSPENDING AUDIENCE VOTES\nWhen a player has a chance to activate a vehicle, before the player declares which\nvehicle he or she is going to activate or is forced to pass, the player may announce\nthat they are spending Audience Votes. A player may use Audience Votes in this\nway even if they have no qualifying vehicles.\nImportantly, this means that if it is your turn to activate a vehicle, but you have\nno qualifying vehicles, you still get a single opportunity to spend Audience\nVotes before you pass, which can then cause you to have a qualifying vehicle\nto activate.\nIn addition, this means that when a Gear Phase begins, if no vehicles\ncurrently qualify for an activation in this Gear Phase, each player still gets one\nchance to spend votes before they are forced to pass.\nAUDIENCE VOTE EFFECTS\nWhen a player has an opportunity to spend Audience Votes, that player may\nspend any number of Audience Votes to declare any number of effects.\nBURN RUBBER (1 AUDIENCE VOTE)\nSelect any vehicle you control. That vehicle may immediately change Gear, either\none up or one down, gaining 1 Hazard Token as normal. Use of this effect can\nallow you to declare an activation with a vehicle that was previously unable to\nactivate in this Gear Phase.\nTHUNDEROUS APPLAUSE (1 AUDIENCE VOTE)\nSelect a vehicle you control. Immediately remove D6 Hazard Tokens from that\nvehicle.\nEXECUTIVE INTERVENTION (2 AUDIENCE VOTES)\nSelect a vehicle you do not control. The selected vehicle immediately gains Hazard\nTokens until it has 5 Hazard Tokens.\nRELOAD (2 AUDIENCE VOTES)\nSelect a single weapon or upgrade on a vehicle you control. The selected weapon\nor upgrade immediately gains 1 Ammo Token."
    },
    {
        "page": "Page 91",
        "title": "CARPE DIEM (2 AUDIENCE VOTES)",
        "text": "90\nCARPE DIEM (2 AUDIENCE VOTES)\nImmediately move Pole Position to a player of your choice or prevent Pole\nPosition from moving the next time it would be moved.\nRESPAWN (3 AUDIENCE VOTES)\nYou may only use this effect if you have no vehicles currently in play. Select a\nvehicle that you controlled that has been Wrecked during this game and respawn\nit. The vehicle regains Hull Points equal to half its Hull Value, rounded down.\nWhen respawning a vehicle that is still in play as a wreck, turn its wreck back over\nto become a vehicle. When respawning a vehicle that is not currently in play,\nfollow the rules given in the scenario."
    },
    {
        "page": "Page 92",
        "title": "SPONSORS",
        "text": "91\nSPONSORS\nWith the promise of the right to ascend to the shining Martian pleasure domes,\nthere are many who are ready to generously sponsor new teams. Each sponsor has\nlucrative advertising deals in place, of course.\nA team may choose a Sponsor. This Sponsor immediately grants the team all\nof the Sponsored Perks for that Sponsor. The choice of Sponsor determines what\nperks classes this team may purchase from.\nRUTHERFORD\nGrant Rutherford is the son of a militaristic, American, oil baron. He is aggressive,\nrich, and uncompromising. His beaming face, beneath his trademark cream Stetson,\nadorns billboard advertisements for his high-quality and high-priced Rutherford brand\nweaponry. Teams sponsored by Rutherford gain access to military surplus, missile\nlaunchers, tanks, helicopters, and as much ammo as they can carry. After his team won\nin 2016, he was only too happy to kiss the Earth goodbye and now runs his company\nfrom his, highly exclusive, Martian office.\n\u2022\t Perk Classes: Badass and Military.\nTeams sponsored by Rutherford gain the following Sponsored Perks:\n\u2022\t Military Hardware: This team may purchase a single Tank. This team\nmay purchase a single Helicopter.\n\u2022\t Well Stocked: This vehicle considers any weapon with the ammo 3 special\nrule to instead have the ammo 4 special rule when purchased.\n\u2022\t Might Is Right: This team may not purchase Lightweight vehicles.\n\u2022\t Televised Carnage: If this vehicle causes 6 or more hits in a single Attack\nStep, before Evades, the controller of this vehicle gains 1 Audience Vote."
    },
    {
        "page": "Page 93",
        "title": "MIYAZAKI",
        "text": "92\nMIYAZAKI\nYuri Miyazaki grew up in the rubble of Tokyo, fighting her way to the top of the speedway\ncircuit with incredible feats of daring and vehicular agility. She has a small fleet of elite\ncouriers who run jobs for the wealthiest or most desperate clients. It is whispered that she\nalso runs guns for the Pro-Earth Resistance, but no one who spreads that rumour lives long\nenough to spread it far. Miyazaki\u2019s drivers are unsurpassed in their skill and finesse.\n\u2022\t Perk Classes: Daring and Precision.\nTeams sponsored by Miyazaki gain the following Sponsored Perks:\n\u2022\t Virtuoso: The first time this ehicle Pushes It during an activation, this\nvehicle may Push It without gaining a Hazard Token.\n\u2022\t Elegance: Teams sponsored by Miyazaki may not purchase vehicle types\nwith a base Handling Value of 2 or lower.\n\u2022\t Showing Off: At the end of this vehicle\u2019s activation, if it resolved at least one\nSpin result, and resolved at least one Slide result, and changed Gear at least\nonce, and did not Wipeout, then this vehicle gains a Showing Off token.\nIf a vehicle with a Showing Off token wipes out, that vehicle must discard\nits Showing Off token.\nAt the end of this vehicle\u2019s activation, if every in-play vehicle on this team\nhas a Showing Off token, this player discards all Showing Off tokens and\ngains 1 Audience Vote for each Showing Off token discarded in this way.\nDiscard all Showing Off tokens at the end of the Gear Phase.\n92"
    },
    {
        "page": "Page 94",
        "title": "MISHKIN",
        "text": "93\nMISHKIN\nAndre Mishkin is not a natural sportsman. However, the brilliant Russian engineer\nand inventor proved in 2010 that technology is just as solid an answer as skill or\nferocity on the track. From his research and development facility on Mars he continues\nto send designs for unusual and devastating weapons and sleek, hi-tech vehicles to\nEarth for field-testing by the teams he sponsors.\n\u2022\t Perk Classes: Military and Technology.\nTeams sponsored by Mishkin gain the following Sponsored Perks:\n\u2022\t Thumpermonkey: This team may purchase electrical weapons and\nupgrades.\n\u2022\t Dynamo: After activating in Gear Phase 4, 5, or 6, this vehicle may add\n+1 Ammo Token to a single electrical weapon or electrical upgrade on that\nvehicle.\n\u2022\t All the Toys: Whenever a vehicle in this team attacks with a named\nweapon that has not been attacked with by any vehicle during this game\nyet, that vehicle\u2019s controller gains 1 Audience Vote."
    },
    {
        "page": "Page 95",
        "title": "IDRIS",
        "text": "IDRIS\nYandi Idris was an addict. From the first time the hot and sweet fumes of a singing\npetrol engine filled his nose he could find no other joy. He said that the first time he\npressed that nitro-oxide button was like touching the face of God. Mystical, irrational,\nand dangerous, the Cult of Speed spread like wildfire after Idris\u2019 meteoric rise during\nthe 2012 Gaslands season. He crossed the final finishing line in a ball of fire and his\nbody was never found. His fanatical followers say that at 201mph you can hear his\nsonorous voice on the rushing head wind.\n\u2022\t Perk Classes: Precision and Speed.\nTeams following in Idris\u2019 tire tracks gain the following Sponsored Perks:\n\u2022\t N2O Addict: This team may purchase the Nitro upgrade at half the listed\ncost.\n\u2022\t Speed Demon: When this vehicle gains Hazard Tokens as a result of the\nNitro Booster, this vehicle only gains Hazard Tokens until it has 3 Hazard\nTokens, rather than 5 Hazard Tokens.\n\u2022\t Cult of Speed: During Gear Phase 1, 2, or 3 if this vehicle selects the\nLong Straight movement template, including when using the Nitro\nBooster upgrade, this vehicle\u2019s controller gains 1 Audience Vote.\n\u2022\t Kiss My Asphalt: This team may not purchase Gyrocopters.\n\nRemember that you can select any template you like (and thus trigger the Cult\nof Speed rule, but if it is not permitted, the player to your left will get to select\nyour template instead."
    },
    {
        "page": "Page 95",
        "title": "IDRIS",
        "text": "IDRIS\nYandi Idris was an addict. From the first time the hot and sweet fumes of a singing\npetrol engine filled his nose he could find no other joy. He said that the first time he\npressed that nitro-oxide button was like touching the face of God. Mystical, irrational,\nand dangerous, the Cult of Speed spread like wildfire after Idris\u2019 meteoric rise during\nthe 2012 Gaslands season. He crossed the final finishing line in a ball of fire and his\nbody was never found. His fanatical followers say that at 201mph you can hear his\nsonorous voice on the rushing head wind.\n\u2022\t Perk Classes: Precision and Speed.\nTeams following in Idris\u2019 tire tracks gain the following Sponsored Perks:\n\u2022\t N2O Addict: This team may purchase the Nitro upgrade at half the listed\ncost.\n\u2022\t Speed Demon: When this vehicle gains Hazard Tokens as a result of the\nNitro Booster, this vehicle only gains Hazard Tokens until it has 3 Hazard\nTokens, rather than 5 Hazard Tokens.\n\u2022\t Cult of Speed: During Gear Phase 1, 2, or 3 if this vehicle selects the\nLong Straight movement template, including when using the Nitro\nBooster upgrade, this vehicle\u2019s controller gains 1 Audience Vote.\n\u2022\t Kiss My Asphalt: This team may not purchase Gyrocopters.\n\nRemember that you can select any template you like (and thus trigger the Cult\nof Speed rule, but if it is not permitted, the player to your left will get to select\nyour template instead."
    },
    {
        "page": "Page 96",
        "title": "SLIME",
        "text": "95\nSLIME\nSlime rules a wild and feral city in the Australian wastes known as Anarchy. Young\npeople crawled out of the wreckage of the scorched earth in their thousands to rally\nround her ragged banner. The wild-eyed and whooping joyful gangs of Anarchy are\nled by Slime\u2019s henchwomen, the Chooks, who seek fame and adoration from the\nglobal Gaslands audience.\n\u2022\t Perk Classes: Tuning and Reckless.\nTeams sponsored by Slime gain the following Sponsored Perks:\n\u2022\t Pinball: If this vehicle is involved in a Collision during its Movement Step\nin which the point of contact on both vehicles is along their side edges,\nand this vehicle declares a Smash Attack, then this vehicle may\nimmediately resolve another Movement Step after the current Movement\nStep.\n\u2022\t Spiked Fist: This team counts the Ram upgrade as requiring zero build\nslots.\n\u2022\t Live Fast: During this vehicle\u2019s activation, if this vehicle begins the\nWipeout Step with more Hazard Tokens than Hull Points, this vehicle\u2019s\ncontroller gains 1 Audience Vote.\n95"
    },
    {
        "page": "Page 97",
        "title": "THE WARDEN",
        "text": "96\nTHE WARDEN\nWarden Cadeila is proud to live in S\u00e3o Paulo, a shining hub of humanity and\nrelatively untouched by the war. The S\u00e3o Paulo People\u2019s Penitentiary has produced\nthree of Gaslands\u2019 top ten teams in the past decade, and the Warden continues to grant\nher prisoners a chance at freedom as long as the Gaslands franchise continues to deliver\nthe sponsorship deals. The deal isn\u2019t great for the damned souls who are welded into the\nWarden\u2019s solid steel \u201ccoffin cars\u201d, but it\u2019s better than the alternative.\n\u2022\t Perks Classes: Aggression and Badass.\nTeams sponsored by the Warden gain the following Sponsored Perks:\n\u2022\t Prison Cars: Vehicles in this team may purchase the following upgrade:\n\u201cPrison Car: Reduce the base cost of this vehicle by 4 Cans (to a\nminimum of 5 Cans). Reduce the Hull Value of this vehicle by 2. May\nonly be purchased by Middleweight vehicles. May only be purchased once\nfor each vehicle.\n\u2022\t Fireworks: If this vehicle Explodes, its controller gains 1 Audience Vote if\nit was Middleweight or 2 Audience Votes if it was Heavyweight, in\naddition to any votes gained for it being Wrecked. Then discard all Ammo\nTokens from the wreck."
    },
    {
        "page": "Page 98",
        "title": "\u00a9 Sven Siewert",
        "text": "\u00a9 Sven Siewert\nSCARLETT\nGaslands is able to support a vast ecosystem of villainous and scurvy raiders, picking off\nricher teams as their rigs roll from one televised race to the next. Many of these self-styled\npirate crews have gained renown, but none have rivalled the infamy or showmanship of\nScarlett Annie.  A dashing and flamboyant buccaneer, her cult following is likely more\nto do with her canny association with the long-running \u201cDeath Valley Death Run\u201d\ndocumentary TV series than any particular skill at dust bowl piracy.\n\u2022\t Perk Classes: Tuning and Aggression.\nTeams throwing their lot in with Scarlett gain the following Sponsored Perks:\n\u2022\t Crew Quarters: This team may purchase the Extra Crewmember upgrade\nat half the listed cost.\n\u2022\t Raiders:  At the end of the Attack Step, this vehicle may permanently\nreduce its Crew Value by any number, to a minimum of 0 crew. Remove 1\nHull Point from any vehicle in base contact for each crew removed in this\nway.\n\u2022\t Raise the Sails: After rolling Skid Dice, this vehicle may permanently\nreduce its Crew Value by 1, to a minimum of 0 crew to add 1 free Shift\nresult to the Skid Dice result.\n\u2022\t Press Gang or Keelhaul: When another vehicle in contact\nwith this vehicle is Wrecked, this vehicle may either gain 1 crew\nor gain 2 Audience Votes."
    },
    {
        "page": "Page 99",
        "title": "HIGHWAY PATROL",
        "text": "98\nHIGHWAY PATROL\nAlong the Wrecked and broken highways, where law is another word for vengeance,\nand justice is a forgotten memory; a handful of souls still cling to a dream of order.\nPerhaps they do it for the glory. Maybe they even get a kick out of it. They are\nunsanctioned, unloved and unpaid. Their only power: a badge of bronze. Their only\nweapon: 600 horsepower of fuel-injected steel. The Highway Patrol are the last law\nin a world gone crazy.\n\u2022\t Perk Classes: Speed and Pursuit.\nTeams sponsored by Highway Patrol gain the following Sponsored Perks:\n\u2022\t Hot Pursuit: Before the first ear Phase of the game, after deployment,\nthis team must nominate one enemy vehicle as the \u201cbogey\u201d. If the bogey is\nWrecked or disqualified, immediately nominate another enemy ehicle to\nbe the bogey.\n\u2022\t Bogey at 12 o\u2019Clock: At the end of this vehicle\u2019s Movement Step, if the\nbogey in is this vehicle\u2019s front Arc of Fire, and further than Double Range\naway, and can be seen by this vehicle, this vehicle may immediately resolve\nanother Movement Step.\n\u2022\t Siren: At the end of this vehicle\u2019s Attack Step, if this vehicle is in the\nbogey\u2019s rear Arc of Fire (regardless of range), the bogey must either reduce\nits Gear by 1 or gain 2 Hazard Tokens.\n\u2022\t Steel Justice: If the bogey wipes out, this team, as a whole, gains 2 Audience\nVotes. If the bogey is Wrecked this team, as a whole, gains 4 Audience Votes\nTeams sponsored by Highway Patrol may purchase the following upgrade:\n\u2022\t Louder Siren (2 Cans): Replace \u201cbogey\u201d with \u201cany enemy vehicle\u201d for the\npurposes of the Siren special rules.\nVERNEY\nMany have taken the bent deal offered by Warden Cadeila but only one has ever\nearned their freedom. As skilled an engineer as he is a driver, the newly-freed Verney\nnow specialised in building unique Frankenstein\u2019s monsters of vehicles for anyone who\ncan afford his high-quality customs."
    },
    {
        "page": "Page 100",
        "title": "\u2022\t Perk Classes: Technology and Built.",
        "text": "99\n\u2022\t Perk Classes: Technology and Built.\nTeams sponsored by Verney gain the following Sponsored Perks:\n\u2022\t MicroPlate Armour: Vehicles in this team may purchase the MicroPlate\nArmour upgrade, which costs 6 Cans, increases the vehicles Hull Value by\n2, and requires 0 build slots.\n\u2022\t Trunk of Junk: You may attack with any number of dropped weapons in\na single activation.\n\u2022\t Tombstone: If the shooting template of a shooting attack touches the rear\nedge of this vehicle, this vehicle gains +1 to its Evade rolls. During this\nvehicle\u2019s Attack Step, this vehicle may gain 2 Hazard Tokens. If it does, all\nCollisions involving this vehicle are considered to be Head-on until the\nstart of its next activation.\n\u2022\t That\u2019s Entertainment: Whenever a dropped weapon template that was\nplaced by this team is removed from play, this team gains 1 Audience Vote.\nMAXXINE\nMaxxine is the current grease-smeared face of The Black Swans. While many might\nassume art to have been the last thing to survive the Martian bombs, The Black Swans\ndance their mechanised masque for a hypnotised audience. It\u2019s ballet, but the dancers\nweigh 4,000 pounds and are dripping in engine oil.\n\u2022\t Perk Classes: Tuning and Pursuit.\nTeams sponsored by Maxxine gain the following Sponsored Perks:\n\u2022\t Dizzy: This vehicle may resolve any number of Spin results separately\nduring its Movement Step, one after another. This can allow this vehicle to\nSpin more than 90 degrees during its Movement Step.\n\u2022\t Maxximum Drift: If this vehicle resolves two Slide results in a single\nMovement Step, it may use the Medium Straight in place of the slide\ntemplate. If this vehicle resolves three or more Slide results in a single\nMovement Step, it may use the Long Straight in place of the Slide\ntemplate.\n\u2022\t Meshuggah: When this vehicle resolves a Slide or Spin that ends within\nMedium range of a friendly vehicle without causing a Collision, this team\ngains 1 Audience Vote."
    },
    {
        "page": "Page 101",
        "title": "THE ORDER OF THE INFERNO",
        "text": "100\nTHE ORDER OF THE INFERNO\nYandi Idris is not dead. He cannot die. He rides on in the living flame. His voice can\nbe heard in the roar of the road and the screams of superheated metal. Yandi is free,\nand we can be too. He has shown us the path. Only by knowing the flames can we\nknow true freedom. Buy your copy of \u201cFreedom in The Flames\u201d today to find out more.\nAvailable from Order of the Inferno stalls at all major trading outposts.\n\u2022\t Perk Classes: Horror and Speed.\nTeams indoctrinated into The Order of the Inferno gain the following Sponsored\nPerks:\n\u2022\t Fire Walk With Me: When this vehicle would receive damage from any\nweapon or effect with the Fire rule, this vehicle may reduce the damage\nreceived by up to three, to a minimum of one.\n\u2022\t Burning Man: If this vehicle is On Fire it gains +1 to all Evade dice.\n\u2022\t Cult of Flame: At the end of the Gear Phase, if there are more enemy\nvehicles On Fire than there are friendly vehicles On Fire, or all enemy\nvehicles are On Fire, this team gains 1 Audience Vote for each friendly\nvehicle that is On Fire.\nBEVERLY, THE DEVIL ON\nTHE HIGHWAY\nThe low growling of the starting grid was suddenly eclipsed by an ear-splitting,\ndizzying sound. Eyeball-shakingly loud, the shrill screeching was suffocating. A single\ncar drifted forward into the pack, windows like onyx, bumper corroded. The sound\nchanged timbre, dropping suddenly to a sub-audible throb that tightened chests and\nshattered headlamps. Despite the harsh desert sun, frost began to form on windshields.\nBeverly was a stupid story told to scare children. She wasn\u2019t real.\n\u2022\t Perk classes: Horror and Built.\nTeams haunted by Beverly gain the following Sponsored Perks:\n\u2022\t Graveyard Shift: At the start of the game, after deployment, all vehicles in\nthis team except one must gain the Ghost Rider special rule."
    },
    {
        "page": "Page 102",
        "title": "\u2022\t Ghost Rider: This vehicle ignores, and is ignored by, other vehicles at all",
        "text": "\u2022\t Ghost Rider: This vehicle ignores, and is ignored by, other vehicles at all\ntimes. This vehicle cannot be involved in Collisions. This vehicle may not\nmake shooting attacks or be attacked with shooting weapons. This vehicle\nmay never count towards the victory conditions of a scenario.\n\u2022\t Soul Anchor: If all in-play vehicles from this team have the Ghost Rider\nspecial rule immediately remove all vehicles on this team from play.\n\u2022\t At the Crossroads: This team may choose to pay only 1 Audience Vote to\nrespawn a vehicle. If they do, the respawned vehicle must gain the Ghost\nRider special rule.\n\u2022\t Inexorable: If a vehicle from this team is a wreck or out of play, the\nvehicle may be respawned, even if other rules would ordinarily prevent\nthat.\n\u2022\t Soul Harvest: If this vehicle\u2019s movement template comes into contact with\nan enemy vehicle, this vehicle gains 1 Soul Token, even if the enemy\nvehicle is being ignored. If this vehicle\u2019s movement template comes into\ncontact with a friendly vehicle without the Ghost Rider rule that it did not\nstart in contact with, choose one: either gain 1 Audience Vote for each\nSoul token or repair two Hull Points on the vehicle without the Ghost\nRider rule for each Soul Token. Then discard all Soul Tokens from this\nvehicle.\nA Ghost Rider may gain a Soul Token and give it to a friendly vehicle in the\nsame activation, as long as it would come into contact with the enemy vehicle\nfirst.\n101"
    },
    {
        "page": "Page 103",
        "title": "RUSTY\u2019S BOOTLEGGERS",
        "text": "102\nRUSTY\u2019S BOOTLEGGERS\nZeke Rusty and his boys been wall to wall and treetop-tall since before the world went\nto hell, running moonshine past Smokey back since before the big red one fell. Their\nstills are volatile, their delivery vehicles are ramshackle, but they still run liquor that\ngrandpappy would be proud of... though none the boys can remember just how he\nliked it right now. Damn that gin.\n\u2022\t Perk class: Reckless and Built.\nTeams rum-running for Rusty gain the following Sponsored Perks:\n\u2022\t Party Hard: At the end of this vehicle\u2019s Attack Step, if this vehicle has\nmore Hazard Tokens than the sum of the Hazard Tokens on all other\nenemy vehicles within Medium range combined, this vehicle\u2019s controller\ngains 1 Audience Vote for each enemy vehicle with one or more Hazard\nTokens within Medium range of this vehicle.\n\u2022\t Dutch courage: Vehicles in this team only Wipeout when they have 8\nHazard Tokens.\n\u2022\t As Straight as I\u2019m Able: This vehicle does not gain a Hazard Token from\nthe articulated rule if it selects a template that is not a Straight.\n\u2022\t Over the Limit: This vehicle never considers any of the Straight\nmovement templates to be permitted. This vehicle considers Veer to be\npermitted and Trivial in any Gear.\n\u2022\t Trailer Trash: This team may purchase Trailers. This team must contain\neither: one or more Medium or Heavyweight vehicles equipped with a\ntrailer upgrade, or a War Rig.\n\u2022\t Haulage: Each vehicle on this team equipped with a trailer upgrade, and\neach War Rig on this team, may equip a single trailer cargo upgrade for\nfree.\nTRAILERS\nA trailer is an upgrade. A vehicle may be equipped with a single trailer. A War Rig\nmay not be equipped with the trailer upgrade. A vehicle equipped with a trailer\ngains the Articulated, Ponderous, and Piledriver special rules, (see War Rig, page\n116)"
    },
    {
        "page": "Page 104",
        "title": "\u2022\t Stowage: Middleweight trailers provide 1 additional build slot to the",
        "text": "103\n\u2022\t Stowage: Middleweight trailers provide 1 additional build slot to the\ntowing vehicle. Heavyweight trailers provide 3 additional build slots to the\ntowing vehicle. When purchasing a weapon for a vehicle with a trailer, the\nplayer must declare whether that weapons is installed on the cab or the\ntrailer. When measuring range, place the shooting template touching\neither the cab or the trailer, depending on where the weapon is mounted,\nas per the Articulated rules (see War Rig, page 118).\nTRAILER CARGO\nWhere indicated, a vehicle equipped with a trailer upgrade, or War Rig, may\nequip a single trailer cargo upgrade.\n\u2022\t Peach Moonshine: This vehicle\u2019s Molotov Cocktails count as having an\ninfinite number of Ammo Tokens.\n\u2022\t Sourmash Jet Booster: At the end of this vehicle\u2019s Movement Step, if this\nvehicle has 5 or more Hazard Tokens, it must immediately make a forced\nmove Long Straight directly forward. This ignores Over the Limit special rule.\n\u2022\t Siphon Pump: At the start of this vehicle\u2019s Attack Step, regardless of\nwhether it is Distracted, this vehicle may take up to one Hazard Token\nfrom each vehicle within Short range of it and place it on this vehicle.\n\u2022\t Old Fashioned Corn Liquor: Whenever a vehicle within Medium range\nof this vehicle gains one or more Hazard Tokens, it gains one additional\nHazard Token.\n\u2022\t Cattle-Hammer: This vehicle may consider its current Gear to be any\nvalue, up to this vehicle\u2019s max Gear, during the Wipeout Step, including\nduring any Collisions resolved during the Wipeout Step.\nTRAILER UPGRADE TABLE\nUpgrades\nSpecial Rules\nBuild Slots\nCost\nTrailer (Lightweight)\nTrailer. Restricted. Stowage.\n-\n4\nTrailer (Middleweight)\nTrailer. May only be purchased for middleweight and\nheavyweight vehicles. Restricted. Stowage.\n(+1)\n8\nTrailer (Heavyweight)\nTrailer. May only be purchased for heavyweight vehicles.\nRestricted. Stowage.\n(+3)\n12"
    },
    {
        "page": "Page 105",
        "title": "PERKS",
        "text": "104\nPERKS\nPerks represent the skills and experience of the members of your team and allow\nyou to further personalise your team. They are divided into a set of perk classes.\nVehicles may only purchase perks from those perks classes lists under their chosen\nsponsor.\nThere is no limit to the number of perks each vehicle can have. Each perk may\nonly be purchased once for each vehicle.\nAGGRESSION\nDOUBLE-BARRELED (2 CANS)\nDuring this vehicle\u2019s Attack Step, up to three weapons with the Crew Fired special\nrule may gain a +1 bonus to hit.\nBOARDING PARTY (2 CANS)\nThis vehicle ignores the Distracted rule, meaning this vehicle may attack during\nthe Attack Step even if the vehicle is touching an obstacle.\nBATTLEHAMMER (4 CANS)\nWhen making a Smash Attack, this vehicle gains +1 attack die for each Hazard\nToken it currently has.\nTERRIFYING LUNATIC (5 CANS)\nWhenever a vehicle controlled by another player ends its Movement Step within\nShort range of this vehicle, the active vehicle gains a Hazard Token."
    },
    {
        "page": "Page 106",
        "title": "GRINDERMAN (5 CANS)",
        "text": "105\nGRINDERMAN (5 CANS)\nBefore this vehicle rolls its attack dice in a Smash Attack, it may choose to add 1\nHazard Token to the target vehicle for each point of damage it inflicts, instead of\nremoving Hull Points.\nMURDER TRACTOR (5 CANS)\nThis vehicle may make piledriver attacks, like a War Rig.\nBADASS\nPOWDER KEG (1 CAN)\nThis vehicle may add 1 to its explosion check. Treat this vehicle as one weight-\nclass heavier when it explodes. This bonus does apply during resolution of the\nFireworks perk.\nCROWD PLEASER (1 CAN)\nIf this vehicle wipes out, gain 1 Audience Vote.\nROAD WARRIOR (2 CANS)\nOnce per activation, if this vehicle has successfully caused one or more hits on an\nenemy vehicle at any point during this activation, this vehicle may remove a\nsingle Hazard Token at the end of its Attack Step.\nCOVER ME (2 CANS)\nOnce during its activation, this vehicle may remove a Hazard Token and place it\non another friendly vehicle within Double range.\nMADMAN (3 CANS)\nAt the end of this vehicle\u2019s Movement Step, if it has 4 or more Hazard Tokens, it\nmay remove a Hazard Token and place it on another vehicle within Medium range.\nBULLET-TIME (3 CANS)\nIf this vehicle resolves a Slide result during its Movement Step, this may select one\nof its weapons to count as Turret-mounted for the rest of the activation."
    },
    {
        "page": "Page 107",
        "title": "BUILT",
        "text": "106\nBUILT\nDEAD WEIGHT (2 CANS)\nDuring this vehicle\u2019s Attack Step, this vehicle may gain 2 Hazard Tokens to count\nas one weight-class heavier (unless already Heavyweight) until the start of its next\nactivation.\nBARREL ROLL (2 CANS)\nWhen this vehicle suffers a Flip, it may choose to place the Flip template touching\nthe centre of either side edge or the rear edge of this vehicle, and perpendicular to\nthat edge, instead of touching the front edge as normal.\nBRUISER (4 CANS)\nIn a Collision involving this vehicle, if this vehicle declares a reaction other than\nEvade against an enemy vehicle, the enemy vehicle immediately gains one Hazard\nToken.\nSPLASHBACK (5 CANS)\nOnce per step, when this vehicle loses one or more Hull Points, make a 1D6\nattack against each vehicle within Medium range at end of that step.\nCRUSHER (7 CANS)\nThis vehicle gains the Up and Over special rule (See the Monster Truck rules,\npage 71).\nFEEL NO PAIN (8 CANS)\nDuring an enemy vehicle\u2019s Attack Step, after an attacker has rolled all their attack\ndice against this vehicle, if the attacks caused a total of 2 or fewer uncancelled\nhits, cancel all remaining hits.\n\u00a9 Jake Zettelmaier"
    },
    {
        "page": "Page 108",
        "title": "DARING",
        "text": "107\nDARING\nCHROME-WHISPERER (2 CANS)\nThis vehicle may Push It any number of times during a single Movement Step,\ngaining 1 Hazard Token each time.\nSLIPPERY (3 CANS)\nVehicles making a Smash Attack targeting this vehicle suffer a penalty of -2 attack\ndice.\nHANDBRAKE ARTIST (3 CANS)\nWhen applying a Spin result, this vehicle may choose to face any direction.\nEVASIVE (5 CANS)\nBefore making an Evade roll, this vehicle may gain any number of Hazard Tokens\nto add +1 to each of their Evade dice for each Hazard Token gained. A roll of a\n\u201c1\u201d on an Evade dice always counts as a failure.\nPOWERSLIDE (5 CANS)\nThis vehicle may use any template except the long straight template instead of the\nslide template when applying a slide result. As with the step 1.1 of Movement\nStep, you must use the first movement template you touch. Treat the selected\nmovement template as a slide template for purposes of finding the vehicle\u2019s Final\nPosition.\nSTUNT DRIVER (7 CANS)\nThis perk may only be taken on a lightweight or middleweight vehicle type with\na base Handling Value of 3 or more. This vehicle may choose to ignore any\nnumber of obstructions during its Movement Step. After any Movement Step in\nwhich this vehicle chose to ignore any obstruction using this ability, this vehicle\nimmediately gains 3 Hazard Tokens."
    },
    {
        "page": "Page 109",
        "title": "HORROR",
        "text": "108\nHORROR\nPURIFYING FLAMES (1 CAN)\nOnce per activation, at the start of this vehicle\u2019s activation, this vehicle may suffer\nup to three damage to select any friendly vehicle. For each point of damage\nsuffered via this effect, repair that number of Hull Points on the target vehicle.\nThis damage may not be reduced. This damage counts as having the Fire rule.\nThis effect may not be used to raise a vehicle above its starting Hull Value.\nECSTATIC VISIONS (1 CAN)\nOnce per activation, at the start of this vehicle\u2019s activation, this vehicle may gain\nup to 3 Hazard Tokens to discard 1 Hazard Token from a friendly vehicle for each\nHazard Token gained.\nSYMPATHY FOR THE DEVIL (1 CAN)\nWhen this vehicle makes an Evade check, its controller may select a friendly\nvehicle within Medium range. Add the current Gear of the selected vehicle to this\nvehicle\u2019s current Gear for the purposes of this evade check. Both the selected\nvehicle and this vehicle suffer any unsaved damage from this attack, including\nany additional effects.\nHIGHWAY TO HELL (2 CANS)\nAt the end of its Movement Step, if this vehicle selected a straight template, this\nvehicle may suffer two damage. This damage counts as having the Fire rule. If any\nHull Points are removed by this effect, this vehicle may leave its movement\ntemplate (ignoring any slide template) in play as a Napalm dropped weapon\ntemplate. Remove this template at the start of this vehicle\u2019s next activation. (You\nmay wish to download and print out extra paper templates for this effect.)\nVIOLENT MANIFESTATION (3 CANS)\nWhen this vehicle is respawned: make an immediate attack (with attack dice\nbased on the weight of the respawned vehicle) against every other vehicle within\nMedium range as if this vehicle was an exploding wreck. This explosion counts as\nhaving both the \u201cBlast\u201d and \u201cFire\u201d rules.\nANGEL OF DEATH (4 CANS)\nBefore making an attack, this vehicle may suffer up to three damage to add that\nmany attack dice to a single weapon used in this attack."
    },
    {
        "page": "Page 110",
        "title": "MILITARY",
        "text": "MILITARY\nDEAD-EYE (2 CANS)\nDuring this vehicle\u2019s Attack Step, this vehicle gains +1 bonus to hit if making a\nshooting attack at a target within Double range and not within Medium range.\nCritical Hits still occur only on the natural roll of a 6.\nLOADER (2 CANS)\nAt the start of its Attack Step, this vehicle may temporarily reduce its Crew Value\nby one, once, until the end of the Attack Step, to gain +1 bonus to hit with a\nsingle weapon. Critical Hits still occur only on the natural roll of a 6.\nFULLY LOADED (2 CANS)\nIf a shooting weapon on this vehicle has 3 or more Ammo Tokens remaining\nbefore discarding an Ammo Token to attack, that weapon gains +1 attack die.\nRAPID FIRE (2 CANS)\nOnce per round, after attacking with a weapon, this vehicle may resolve an\nadditional Attack Step in which it may only attack with that weapon.\nHEADSHOT (4 CANS)\nWhen making a shooting attack, this vehicle\u2019s Critical Hits inflict 3 hits instead\nof the normal two hits.\nRETURN FIRE (5 CANS)\nOnce per Gear Phase, if this vehicle is the target of a shooting attack, this vehicle\nmay take 2 Hazard Tokens to immediately attack, as if it was this vehicle\u2019s Attack\nStep."
    },
    {
        "page": "Page 111",
        "title": "PRECISION",
        "text": "110\nPRECISION\nMISTER FAHRENHEIT (2 CANS)\nThis vehicle cannot gain more than 2 Hazard Tokens from Collisions during a\nsingle activation.\nMOMENT OF GLORY (2 CANS)\nOnce per game, after rolling the Skid Dice, but before resolving the results, this\nvehicle may immediately change any number of Skid Dice to any results they\nchoose.\nRESTRAINT (2 CANS)\nWhen this vehicle would gain a Hazard Token for shifting down a Gear, this\nvehicle may remove one Hazard Token instead.\nEXPERTISE (3 CANS)\nThis vehicle adds 1 to its Handling Value.\nTRICK DRIVING (3 CANS)\nThis vehicle may select a movement template as if its current Gear was one higher\nor one lower.\nEASY RIDER (5 CANS)\nOnce per round, this vehicle may discard one rolled Skid Dice result before\napplying the results."
    },
    {
        "page": "Page 112",
        "title": "PURSUIT",
        "text": "PURSUIT\nON YOUR TAIL (2 CANS)\nWhen an enemy vehicle resolves a Spin or Slide move that ends within Short\nrange of this vehicle, that enemy vehicle gains 1 Hazard Token.\nSCHADENFREUDE (2 CANS)\nIf another vehicle wipes out within Short range of this vehicle, (either before or\nafter any Flip), remove all Hazard Tokens from this vehicle.\nTAUNT (2 CANS)\nAt the start of this vehicle\u2019s Attack Step, roll a Skid Die. If you roll something\nother than a Shift result, you may place that Skid Dice result onto the dashboard\nof a target vehicle within Short range. This Skid Dice result must be resolved\nduring that vehicle\u2019s next Movement Step, and may not be re-rolled.\nOUT RUN (2 CANS)\nAt the start of this vehicle\u2019s Attack Step, all vehicles within Short range of this\nvehicle and in a lower current Gear than this vehicle gains 1 Hazard Token.\nPIT (4 CANS)\nDuring this vehicle\u2019s activation, if this vehicle is involved in a non-head-on\nCollision with an enemy vehicle, it may declare a \u201cPursuit Intervention Technique\u201d\n(PIT) as its reaction, targeting the enemy vehicle, instead of declaring a Smash\nAttack or an Evade. If this vehicle declares a PIT, it may select any movement\ntemplate the target vehicle considers Hazardous in its current Gear. Immediately\nafter the resolution of this Collision, the target vehicle must make a forced move\ndirectly forward using the selected movement template.\nUNNERVING EYE CONTACT (5 CANS)\nEnemy vehicles within Short range of this vehicle may not use Shift results to\nremove Hazard Tokens from their dashboard."
    },
    {
        "page": "Page 113",
        "title": "RECKLESS",
        "text": "112\nRECKLESS\nDRIVE ANGRY (1 CAN)\nAt the start of this vehicle\u2019s activation, this vehicle gains 1 Hazard Token.\nHOG WILD (2 CANS)\nDuring a Collision resolved during a Wipeout Step, this vehicle gains +2 Smash\nAttack dice.\nIN FOR A PENNY (2 CANS)\nIf this vehicle has gained six or more Hazard Tokens during this activation, it may\ndouble the attack dice of any Smash Attack it makes for the remainder of this\nactivation.\nDON\u2019T COME KNOCKING (4 CANS)\nAt the start of this vehicle\u2019s activation, it may gain 4 Hazard Tokens. If it does,\nthis vehicle cannot gain or lose any Hazard Tokens by any means until the start\nof its next activation.\nBIGGER\u2019N YOU (4 CANS)\nIf this vehicle is involved in a Collision, double any Smash Attack bonuses or\npenalties resulting from weight differences during that Collision.\nBEERSERKER (5 CANS)\nWhen this vehicle would suffer damage outside of its activation, reduce that\ndamage by 1, to a minimum of 1."
    },
    {
        "page": "Page 114",
        "title": "SPEED",
        "text": "113\nSPEED\nHOT START (1 CAN)\nRoll a D6 at the start of the game. This vehicle starts the game in that Gear. Re-\nroll if this would put the current Gear of the vehicle above its max Gear.\nSLIPSTREAM (2 CANS)\nIf this vehicle is involved in a tailgate Collision during its activation, this vehicle\nmay declare a Slipstream reaction. If they do, the other vehicle may not declare a\nreaction. If this vehicle declares a Slipstream reaction, this vehicle may change up\nor down one Gear and gains a Hazard Token. Neither vehicle gains Hazard\nTokens as a result of this Collision.\nOVERLOAD (2 CANS)\nWhen resolving Skid Dice during the Movement Step, this vehicle may roll one\nadditional Skid Die. If it does, it must change up at least one Gear or gain a Hazard\nToken.\nDOWNSHIFT (3 CANS)\nAt the end of a Movement Step in which this vehicle changed down one or more\nGears, this vehicle may make a forced move Short Straight forward.\nTIME EXTENDED! (3 CANS)\nAt the end of a Movement Step in which this vehicle passes a race gate, this\nvehicle may remove any number of Hazard Tokens.\nHELL FOR LEATHER (5 CANS)\nThis vehicle considers Long Straight to be permitted in any Gear. The Long\nStraight is not considered either Hazardous or Trivial in any Gear."
    },
    {
        "page": "Page 114",
        "title": "SPEED",
        "text": "113\nSPEED\nHOT START (1 CAN)\nRoll a D6 at the start of the game. This vehicle starts the game in that Gear. Re-\nroll if this would put the current Gear of the vehicle above its max Gear.\nSLIPSTREAM (2 CANS)\nIf this vehicle is involved in a tailgate Collision during its activation, this vehicle\nmay declare a Slipstream reaction. If they do, the other vehicle may not declare a\nreaction. If this vehicle declares a Slipstream reaction, this vehicle may change up\nor down one Gear and gains a Hazard Token. Neither vehicle gains Hazard\nTokens as a result of this Collision.\nOVERLOAD (2 CANS)\nWhen resolving Skid Dice during the Movement Step, this vehicle may roll one\nadditional Skid Die. If it does, it must change up at least one Gear or gain a Hazard\nToken.\nDOWNSHIFT (3 CANS)\nAt the end of a Movement Step in which this vehicle changed down one or more\nGears, this vehicle may make a forced move Short Straight forward.\nTIME EXTENDED! (3 CANS)\nAt the end of a Movement Step in which this vehicle passes a race gate, this\nvehicle may remove any number of Hazard Tokens.\nHELL FOR LEATHER (5 CANS)\nThis vehicle considers Long Straight to be permitted in any Gear. The Long\nStraight is not considered either Hazardous or Trivial in any Gear."
    },
    {
        "page": "Page 115",
        "title": "TECHNOLOGY",
        "text": "114\nTECHNOLOGY\nROCKET THRUSTERS (1 CAN)\nWhen this vehicle is moved as part of a Flip, it may choose to use the Long\nStraight, Veer, or Gentle templates instead of the Medium Straight template.\nWHIZBANG (1 CAN)\nAt the start of each game, this vehicle gains a random Speed perk. This perk is lost\nat the end of the game.\nGYROSCOPE (1 CAN)\nAt the start of each game, this vehicle gains a random Daring perk. This perk is\nlost at the end of the game.\nSATELLITE NAVIGATION (2 CANS)\nWhen this vehicle resolves its Skid Dice, this vehicle\u2019s controller may set aside one\nShift result. This vehicle may have any number of Shift results set aside. Any\nvehicle in this team may use these set aside Shift results during a later Movement\nStep, as if they had rolled them in that Movement Step.\nMOBILE MECHANIC (3 CANS)\nOnce per activation, at the start of its Attack Step, this vehicle may temporarily\nreduce its Crew Value by one, once, until the end of the Attack Step, to perform\na field repair. If it does, this vehicle gains 1 Hull Point, which may not take its\nHull Points above the vehicle\u2019s Hull Value.\nEUREKA! (4 CANS)\nOnce per game, at the start of its Attack Step, this vehicle\u2019s controller may declare\nany weapon that this vehicle has not attacked with yet this game. This vehicle\ncounts as being armed with the declared weapon, on a facing of their choice, for\nthe next attack only.\nTUNING\nFENDERKISS (2 CANS)\nWhen this vehicle makes a Smash Attack, this vehicle suffers a penalty of -2\nattack dice. Vehicles making a Smash Attack targeting this vehicle suffer a penalty\nof -2 attack dice."
    },
    {
        "page": "Page 116",
        "title": "REAR DRIVE (2 CANS)",
        "text": "115\nREAR DRIVE (2 CANS)\nThis vehicle may pivot about the centre of its front edge, rather than the centre\nof the vehicle, when resolving Spin results.\nDELICATE TOUCH (3 CANS)\nThis vehicle ignores the hazard icons on movement templates.\nMOMENTUM (3 CANS)\nWhen resolving Skid Dice, this vehicle may set aside a Slide or Spin result to re-\nroll a Skid Dice. This effect may be used multiple times. Skid Dice that are set\naside must be resolved.\nPURRING (6 CANS)\nThis vehicle does not gain more than 1 Hazard Token from Spin results each\nactivation. This vehicle does not gain more than 1 Hazard Token from Slide\nresults each activation. This vehicle does not gain more than 1 Hazard Token\nfrom Hazard results each activation.\nSKIING (6 CANS)\nIf this vehicle has Handling 3 or higher, this vehicle may take 3 Hazard Tokens at\nthe end of its Movement Step to be ignored by other vehicles during their\nMovement Steps until the start of this vehicle\u2019s next activation. If, by ignoring\nthis vehicle in this way, a vehicle\u2019s Final Position would overlap it, move that\nvehicle backwards along their movement template by the minimum amount to\navoid overlapping any obstruction."
    },
    {
        "page": "Page 117",
        "title": "The War Rig is a massive vehicle and behaves in a couple of unique ways on the",
        "text": "116\nThe War Rig is a massive vehicle and behaves in a couple of unique ways on the\ntabletop. It has the Articulated, Ponderous, and Piledriver special rules.\nMODELLING YOUR WAR RIG\nAs you will see the rules surrounding the War Rig require you to treat the cab and\nthe trailer as somewhat separate game elements.\nBecause of this, it is highly recommended that you model your War Rig in\nsuch a way that the cab and trailer can be separated and hinged during play. You\nmight choose to use small magnets, a pin, or peg to connect the two halves while\nallowing them to be separated and hinged during play.\nTHE WAR RIG\n\u00a9 James Hall"
    },
    {
        "page": "Page 118",
        "title": "ARTICULATED",
        "text": "ARTICULATED\nCAB AND TRAILER\nAn articulated vehicle is comprised of two parts: the cab and the trailer. The front\npart of the articulated vehicle is referred to as the cab. The rear part of the\narticulated vehicle is referred to as the trailer. The cab and trailer are connected by\na hitch.\nARMING AN ARTICULATED VEHICLE\nWhen arming an articulated vehicle with a weapon, the player must declare\nwhether that weapon is mounted on the cab or the trailer. When measuring\nrange, place the shooting template touching either the cab or the trailer, depending\non where the weapon is mounted."
    },
    {
        "page": "Page 119",
        "title": "ARTICULATED MOVEMENT",
        "text": "118\nARTICULATED MOVEMENT\nWhen moving an articulated vehicle, the cab is moved like a normal vehicle,\nseparately to the trailer, and then the trailer is place back into contact with the cab\nonce it is in its Final Position.\nTo move an articulated vehicle, follow these steps:\n\u2022\t Select a movement template as normal\n\u2022\t If the vehicle selects any template other than a Straight, it gains 1 Hazard\nToken\n\u2022\t Place the movement template so that it is touching the centre of the front\nedge of the cab\n\u2022\t Optionally, roll and resolve Skid Dice as normal\n\u2022\t Ignoring the trailer, place the cab in its Final Position\n\u2022\t Place the trailer so that it is reconnected with the hitch of the cab, covering\nas much of the surface area of the movement template as possible."
    }
];